### ISSUE TITLE
PEP 8

### ISSUE THREAD

**Issue by Nodraak** [MThibault/HK_Python#1]
FYI, Python has a very strong code style and well defined conventions, defined in [PEP 8](https://www.python.org/dev/peps/pep-0008) (Python Enhancement Proposal).

[In this line](https://github.com/MThibault/HK_Python/blob/master/Cours1_IO/io.py#L6) you should not have any space between the function name and the parenthesis ([ref](https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements))

Close this issue as you want :)

Edit : oups, je viens de me rendre compte que j'ai rédigé en anglais, réflexe, désolé ^^

**Comment by MThibault** [comment]
Merci pour tes retours c'est très gentil.
Ca va me permettre de m'améliorer.
Hésites pas si tu en as d'autres.
Bon we
